general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/theme/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Propo", style = "Italic" }
size = 14.0

[window]
padding.x = 12
padding.y = 0
decorations = "Buttonless"
opacity = 1.0
blur = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
