include ~/.local/state/omarchy/current/theme/kitty.conf

font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 11.0

symbol_map U+1780-U+17FF,U+19E0-U+19FF Noto Sans Khmer ExtraCondensed
modify_font cell_height 115%

window_padding_width 0 10
hide_window_decorations yes
confirm_os_window_close 0

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map shift+enter send_text all \e[13;2u
map alt+shift+enter send_text all \e[13;4u

allow_remote_control socket-only

cursor_shape beam
cursor_blink_interval 0.6 ease-in-out
cursor_stop_blinking_after 15
cursor_trail 1
cursor_trail_decay 0.03 0.12
cursor_trail_start_threshold 0
shell_integration no-cursor
enable_audio_bell no

tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

listen_on unix:${XDG_RUNTIME_DIR}/omarchy-kitty-{kitty_pid}
