add_newline = true
command_timeout = 200

# Top line: Connector + Path
# Bottom line: Connector + Arch icon + Chevron
format = """
[┌──](bold blue) $directory$git_branch$git_status
[└─](bold blue)$character"""

# format = """
# [╭──](bold blue) $directory$git_branch$git_status
# [╰─](bold blue)$character"""

[character]
success_symbol = "[[󰣇](blue) ❯](purple)" 
error_symbol = "[[󰣇](red) ❯](purple)"
vimcmd_symbol = "[󰣇 ❮](cyan)"

[directory]
truncation_length = 4
repo_root_style = "bold purple"
style = "bold cyan"
format = "[$path]($style) "

[git_branch]
symbol = "󰊢 "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
