format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""

[character]
success_symbol = "[󰄛 ❯](bold yellow)"
error_symbol = "[󰄛 ❯](bold red)"
vimcmd_symbol = "[󰄛 ❮](italic)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"
read_only = " ro"

[fill]
symbol = " "
style = "dimmed"

[git_branch]
symbol = " "
style = "bold magenta"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
truncation_length = 20

[git_status]
style = "bold yellow"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
conflicted = "!"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
modified = "~${count}"
untracked = "?${count}"
staged = "+${count}"
deleted = "-${count}"

[cmd_duration]
min_time = 2000
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
disabled = false

[time]
disabled = false
time_format = "%H:%M"
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""

[python]
symbol = "py "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""

[nodejs]
symbol = "node "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""

[rust]
symbol = "rs "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""

[package]
symbol = "pkg "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
disabled = true

[aws]
symbol = "aws "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
disabled = true

[terraform]
symbol = "tf "
style = "dimmed"
format = """$directory$git_branch$git_status$cmd_duration$time$line_break$character"""
disabled = true
